name: "GreetContributor"
on:
  pull_request:
    types: [opened,synchronize]
    
jobs:
  GreetCommitter:    
    runs-on: ubuntu-latest
    steps:
    - name: "Greet contributor"
      uses: ibakshay/greet-contributors-action@v3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        content: "Thank you for contributing to EPF Study Group wiki!\n Please, make sure you read our [guide for contributors](https://epf.wiki/#/contributing). Share you contribution in corresponding Discord channel to get reviews and more collaborators."
